### ISSUE TITLE
problème lors de la connexion au compte juste créé

### ISSUE THREAD

**Issue by benfour** [AlainBartmanDilaw/FootballBets#2]
Lors de la création d'un compte, tout se passe bien.

![Screenshot_2](https://user-images.githubusercontent.com/19651557/64927184-a4a29580-d807-11e9-8ec2-f7a970047ec3.png)

On est ensuite redirigé sur le home en mode connecté.
Lors de l'affichage de la page home, une erreur s'affiche :

![Screenshot_1](https://user-images.githubusercontent.com/19651557/64927181-9ce2f100-d807-11e9-9d66-aadcebcc7c2d.png)

**Comment by AlainBartmanDilaw** [comment]
Corrigé par commit 9ac782a57405e1b66d9331959321f290b4f6645e
La nomenclature mise en place sur les objets de la base n'aurait pas du s'appliquer aux objets d'authentification, car généré par laravel.
